import Navbar from "@/layout/landing/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dsigner",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full h-screen">
      <Navbar />
      <div className="w-full h-[90dvh] flex items-center">{children}</div>
    </main>
  );
}
