import type { Metadata } from "next";
import { Room } from "../Room";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "YDesign",
  description: "Generated by create next app",
};

export default function DesignLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Room>
      <TooltipProvider>{children}</TooltipProvider>
    </Room>
  );
}
